# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: DelhiPollution

on:
  schedule:
    - cron: "2 */6 * * *"
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install wheel
        pip3 install lxml
        pip3 install bootstrapped --no-deps
        pip3 install -r requirements.txt
        
    - name: Run Script
      run: |
        python Delhi_Air_Pollution_Data_Collection.py ${{ secrets.CRED }}
